#!/usr/bin/env python3
"""
Trade Journal Database — SQLite schema and helper functions.

Stores daily analysis, blocked signals, near-misses, trades, and observations
for driving Phase 3+4 optimization decisions.

Database: data/trade_journal.db
"""

import sqlite3
import os
from datetime import datetime

# Project root is 3 levels up from shree/monitoring/trade_journal_db.py
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB_PATH = os.path.join(_PROJECT_ROOT, "data", "trade_journal.db")


def get_connection(db_path: str = DB_PATH) -> sqlite3.Connection:
    """Get a connection to the trade journal database."""
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def init_db(db_path: str = DB_PATH):
    """Create all tables if they don't exist."""
    conn = get_connection(db_path)
    cursor = conn.cursor()

    # --- Daily summary: one row per trading day ---
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS daily_summary (
            date            TEXT PRIMARY KEY,       -- YYYY-MM-DD
            open_price      REAL,
            close_price     REAL,
            high_price      REAL,
            low_price       REAL,
            range_pts       REAL,
            vx_level        REAL,
            or_high         REAL,
            or_low          REAL,
            support_floor   REAL,
            total_trades    INTEGER DEFAULT 0,
            total_wins      INTEGER DEFAULT 0,
            total_losses    INTEGER DEFAULT 0,
            gross_pnl       REAL DEFAULT 0.0,
            net_pnl         REAL DEFAULT 0.0,
            signals_generated   INTEGER DEFAULT 0,
            chop_blocks         INTEGER DEFAULT 0,
            confidence_blocks   INTEGER DEFAULT 0,
            d_near_misses       INTEGER DEFAULT 0,  -- total D touch-band near-misses
            d_near_misses_5pt   INTEGER DEFAULT 0,  -- within 5pts
            notes           TEXT,                   -- free-form daily notes
            created_at      TEXT DEFAULT (datetime('now'))
        )
    """)

    # --- Signals: every signal generated by the strategy ---
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS signals (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            date            TEXT NOT NULL,           -- YYYY-MM-DD
            time            TEXT NOT NULL,            -- HH:MM:SS CST
            signal_type     TEXT NOT NULL,            -- EMA21_PB_LONG, OR_BREAK_LONG, etc.
            direction       TEXT NOT NULL,            -- BUY or SELL
            confidence      REAL,                    -- base confidence (0.70 typically)
            adx             REAL,
            rsi             REAL,
            atr             REAL,
            macd_h          REAL,
            entry_price     REAL,
            stop_loss       REAL,
            take_profit     REAL,
            outcome         TEXT,                     -- EXECUTED, CHOP_BLOCKED, CONF_BLOCKED, RISK_BLOCKED, etc.
            created_at      TEXT DEFAULT (datetime('now'))
        )
    """)

    # --- Blocked signals: signals that were generated but blocked ---
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS blocked_signals (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            date            TEXT NOT NULL,
            time            TEXT NOT NULL,
            signal_type     TEXT NOT NULL,
            direction       TEXT NOT NULL,
            block_reason    TEXT NOT NULL,            -- CHOP_GUARD, CONFIDENCE, COOLDOWN, RISK_GATE, etc.
            confidence_at_block REAL,                -- conf when blocked
            adx             REAL,
            rsi             REAL,
            atr             REAL,
            entry_price     REAL,
            stop_loss       REAL,
            take_profit     REAL,
            -- Hypothetical outcome (filled in later by analysis)
            hypo_outcome    TEXT,                     -- TP_HIT, SL_HIT, UNKNOWN, STILL_OPEN
            hypo_pnl        REAL,                    -- estimated P&L if trade had been taken
            hypo_notes      TEXT,
            created_at      TEXT DEFAULT (datetime('now'))
        )
    """)

    # --- Near misses: signals that almost fired but missed by a small margin ---
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS near_misses (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            date            TEXT NOT NULL,
            time            TEXT NOT NULL,
            signal_type     TEXT NOT NULL,            -- D, E, A, etc.
            miss_reason     TEXT NOT NULL,            -- touch_band, gap_through, adx_close, etc.
            miss_detail     TEXT,                     -- e.g. "high=6833.0 needed=6834.0"
            gap_pts         REAL,                    -- how close the miss was in points
            created_at      TEXT DEFAULT (datetime('now'))
        )
    """)

    # --- Trades: actual executed trades ---
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS trades (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            date            TEXT NOT NULL,
            entry_time      TEXT NOT NULL,
            exit_time       TEXT,
            signal_type     TEXT NOT NULL,
            direction       TEXT NOT NULL,
            entry_price     REAL NOT NULL,
            exit_price      REAL,
            stop_loss       REAL,
            take_profit     REAL,
            outcome         TEXT,                     -- TP_HIT, SL_HIT, TIME_STOP, MANUAL, etc.
            gross_pnl       REAL,
            net_pnl         REAL,
            commission      REAL,
            confidence      REAL,                    -- final confidence at entry
            adx             REAL,
            vx_level        REAL,
            hold_duration_m INTEGER,                 -- minutes held
            notes           TEXT,
            created_at      TEXT DEFAULT (datetime('now'))
        )
    """)

    # --- Observations: free-form notes and pattern observations ---
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS observations (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            date            TEXT NOT NULL,
            category        TEXT NOT NULL,            -- CHOP_GUARD, STOP_LOSS, SIGNAL_QUALITY, VX, PATTERN, etc.
            severity        TEXT DEFAULT 'INFO',      -- INFO, WARNING, CRITICAL, ACTION_NEEDED
            title           TEXT NOT NULL,
            detail          TEXT,
            recommended_fix TEXT,                     -- which fix from the roadmap
            created_at      TEXT DEFAULT (datetime('now'))
        )
    """)

    # --- Decision gate metrics: running tallies for phase gate decisions ---
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS gate_metrics (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            gate_date       TEXT NOT NULL,            -- the decision gate date (e.g. 2026-03-10)
            metric_name     TEXT NOT NULL,            -- e.g. touch_band_near_misses, trades_per_day, chop_blocks
            metric_value    REAL NOT NULL,
            threshold       REAL,                    -- the gate threshold
            gate_met        INTEGER,                 -- 1=met, 0=not met
            computed_from   TEXT,                     -- date range used
            notes           TEXT,
            updated_at      TEXT DEFAULT (datetime('now'))
        )
    """)

    # --- Indexes for common queries ---
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_signals_date ON signals(date)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_blocked_date ON blocked_signals(date)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_near_misses_date ON near_misses(date)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_trades_date ON trades(date)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_observations_date ON observations(date)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_observations_category ON observations(category)")

    conn.commit()
    conn.close()
    return db_path


# ── Helper functions for inserting data ──

def insert_daily_summary(conn, data: dict):
    """Insert or update a daily summary row."""
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    updates = ", ".join([f"{k}=excluded.{k}" for k in data.keys() if k != "date"])
    sql = f"""
        INSERT INTO daily_summary ({cols}) VALUES ({placeholders})
        ON CONFLICT(date) DO UPDATE SET {updates}
    """
    conn.execute(sql, list(data.values()))


def insert_signal(conn, data: dict):
    """Insert a signal record."""
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(f"INSERT INTO signals ({cols}) VALUES ({placeholders})", list(data.values()))


def insert_blocked_signal(conn, data: dict):
    """Insert a blocked signal record."""
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(f"INSERT INTO blocked_signals ({cols}) VALUES ({placeholders})", list(data.values()))


def insert_near_miss(conn, data: dict):
    """Insert a near-miss record."""
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(f"INSERT INTO near_misses ({cols}) VALUES ({placeholders})", list(data.values()))


def insert_trade(conn, data: dict):
    """Insert a trade record."""
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(f"INSERT INTO trades ({cols}) VALUES ({placeholders})", list(data.values()))


def insert_observation(conn, data: dict):
    """Insert an observation."""
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(f"INSERT INTO observations ({cols}) VALUES ({placeholders})", list(data.values()))


def insert_gate_metric(conn, data: dict):
    """Insert or update a gate metric."""
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(f"INSERT INTO gate_metrics ({cols}) VALUES ({placeholders})", list(data.values()))


# ── Query helpers ──

def get_weekly_summary(conn, start_date: str, end_date: str) -> dict:
    """Get aggregated metrics for a date range."""
    row = conn.execute("""
        SELECT
            COUNT(*) as trading_days,
            SUM(total_trades) as total_trades,
            SUM(total_wins) as total_wins,
            SUM(total_losses) as total_losses,
            SUM(net_pnl) as total_pnl,
            SUM(signals_generated) as total_signals,
            SUM(chop_blocks) as total_chop_blocks,
            SUM(d_near_misses) as total_d_near_misses,
            ROUND(CAST(SUM(total_trades) AS REAL) / COUNT(*), 2) as trades_per_day
        FROM daily_summary
        WHERE date BETWEEN ? AND ?
    """, (start_date, end_date)).fetchone()
    return dict(row) if row else {}


def get_blocked_by_reason(conn, start_date: str, end_date: str) -> list:
    """Get blocked signal counts by reason."""
    rows = conn.execute("""
        SELECT block_reason, COUNT(*) as count,
               SUM(CASE WHEN hypo_outcome = 'TP_HIT' THEN 1 ELSE 0 END) as would_have_won,
               SUM(CASE WHEN hypo_outcome = 'SL_HIT' THEN 1 ELSE 0 END) as would_have_lost
        FROM blocked_signals
        WHERE date BETWEEN ? AND ?
        GROUP BY block_reason
        ORDER BY count DESC
    """, (start_date, end_date)).fetchall()
    return [dict(r) for r in rows]


def get_observations_by_category(conn, category: str = None, severity: str = None) -> list:
    """Get observations, optionally filtered."""
    sql = "SELECT * FROM observations WHERE 1=1"
    params = []
    if category:
        sql += " AND category = ?"
        params.append(category)
    if severity:
        sql += " AND severity = ?"
        params.append(severity)
    sql += " ORDER BY date DESC, id DESC"
    rows = conn.execute(sql, params).fetchall()
    return [dict(r) for r in rows]


def get_near_miss_summary(conn, start_date: str, end_date: str) -> dict:
    """Get near-miss stats for decision gate evaluation."""
    row = conn.execute("""
        SELECT
            COUNT(*) as total,
            SUM(CASE WHEN gap_pts <= 1.0 THEN 1 ELSE 0 END) as within_1pt,
            SUM(CASE WHEN gap_pts <= 3.0 THEN 1 ELSE 0 END) as within_3pt,
            SUM(CASE WHEN gap_pts <= 5.0 THEN 1 ELSE 0 END) as within_5pt,
            MIN(gap_pts) as closest_miss,
            AVG(gap_pts) as avg_gap
        FROM near_misses
        WHERE date BETWEEN ? AND ?
    """, (start_date, end_date)).fetchone()
    return dict(row) if row else {}


if __name__ == "__main__":
    path = init_db()
    print(f"✅ Trade journal database initialized: {path}")
