apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mytrader
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mytrader
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
