"""Regime-first, structure-based rules layer for the SPY Options signal bot.

Import surface intentionally minimal — most callers only need
``RulesV2Engine`` and ``RulesV2Config``.

Feature flag
------------
``cfg.rules_v2.enabled`` defaults to False. When False, the manager must
short-circuit and use the legacy pipeline unmodified.

Apr 21 2026 motivation
----------------------
See docs/rules_v2_apr21_postmortem.md (generated by the redesign task).
Five scratches, one loss, zero wins on a day where the dominant afternoon
regime was TREND_DOWN with clean VWAP-reverting pullbacks. Legacy engine
fired stale ORB signals after the move was exhausted and throttled the
high-quality entries during the move itself.
"""
from __future__ import annotations

from .config import (
    ContinuationConfig,
    EntryGateConfig,
    ExitRulesConfig,
    OrbGateConfig,
    PcRatioAlignmentConfig,
    RegimeV2Config,
    RulesV2Config,
    StrikeSelectorConfig,
    ThrottleConfig,
    TimeOfDayConfig,
)
from .engine import EngineInputs, FilterDecision, RulesV2Engine
from .regime import (
    RANGE_BOUND,
    TRANSITION,
    TREND_DOWN,
    TREND_UP,
    RegimeV2Context,
    RegimeV2Detector,
)
from .continuation import ContinuationCandidate, ContinuationDetector
from .strike_selector import StrikePick, select_strike

__all__ = [
    "ContinuationCandidate",
    "ContinuationConfig",
    "ContinuationDetector",
    "EngineInputs",
    "EntryGateConfig",
    "ExitRulesConfig",
    "FilterDecision",
    "OrbGateConfig",
    "PcRatioAlignmentConfig",
    "RANGE_BOUND",
    "RegimeV2Config",
    "RegimeV2Context",
    "RegimeV2Detector",
    "RulesV2Config",
    "RulesV2Engine",
    "StrikePick",
    "StrikeSelectorConfig",
    "TRANSITION",
    "TREND_DOWN",
    "TREND_UP",
    "ThrottleConfig",
    "TimeOfDayConfig",
    "select_strike",
]
