"""
MES 30-Minute Timeframe Strategy

JAN 11 2026: Purpose-built strategy for 30-minute bars.

Key design principles:
1. Wider stops (1x ATR = 6-8 pts) vs 1m scalping stops
2. Focus on trend continuation, not mean reversion
3. Works during Globex/overnight sessions (77% of 30m data)
4. Higher ADX threshold (30m shows stronger trends)
5. Longer hold times (4-8 hours typical)

Signal types:
- EMA_RECLAIM: Price pulls back to EMA and reclaims
- TREND_CONTINUATION: Pullback in established trend
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from ..config import ThirtyMinuteStrategyConfig
from ..utils.logger import logger


@dataclass
class ThirtyMinuteSignal:
    """Signal generated by the 30-minute strategy."""
    
    timestamp: datetime
    action: str  # "BUY", "SELL", "HOLD"
    direction: str  # "LONG", "SHORT", "FLAT"
    signal_type: str  # "EMA_RECLAIM", "TREND_CONTINUATION", etc.
    confidence: float  # 0.0 to 1.0
    stop_loss: float
    take_profit: float
    entry_price: float
    metadata: Dict[str, Any]


class MesThirtyMinuteStrategy:
    """30-minute timeframe strategy for ES/MES futures."""

    name: str = "ES_30m_Overnight"
    
    def __init__(self, config: ThirtyMinuteStrategyConfig):
        self.config = config
        self._last_signal_bar: Optional[int] = None
        self._trades_today: int = 0
        self._current_date: Optional[datetime] = None
        self._warmup_complete: bool = False
        self._cached_data: Optional[pd.DataFrame] = None  # indicator-enriched data
        
    def reset(self) -> None:
        """Reset strategy state for new backtest."""
        self._last_signal_bar = None
        self._trades_today = 0
        self._current_date = None
        self._warmup_complete = False
        self._cached_data = None

    # ------------------------------------------------------------------
    # Engine-compatible interface: generate(features) -> Signal
    # ------------------------------------------------------------------
    def generate(self, features: pd.DataFrame) -> "Signal":
        """Engine-compatible wrapper around generate_signal().

        The backtest engine calls ``strategy.generate(history)`` and expects
        a ``Signal(action, confidence, metadata)`` back.  This adapts the
        30m strategy's richer ``ThirtyMinuteSignal`` to that contract.
        """
        from .base import Signal

        bar_idx = len(features) - 1

        # Compute indicators once per growing window (idempotent)
        data = self._calculate_indicators(features)

        sig = self.generate_signal(data, bar_idx, current_position=0)

        metadata: Dict[str, Any] = dict(sig.metadata) if sig.metadata else {}
        metadata["stop_loss"] = sig.stop_loss
        metadata["take_profit"] = sig.take_profit
        metadata["entry_type"] = sig.signal_type
        metadata["entry_reason"] = sig.signal_type
        metadata["reason"] = sig.signal_type
        metadata["entry_module"] = "MesThirtyMinuteStrategy"
        metadata["session_type"] = "OVERNIGHT"

        return Signal(
            action=sig.action,
            confidence=sig.confidence,
            metadata=metadata,
        )

    def _check_daily_reset(self, timestamp: datetime) -> None:
        """Reset daily counters if new trading day."""
        current_date = timestamp.date()
        if self._current_date != current_date:
            self._current_date = current_date
            self._trades_today = 0
            
    def _calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """Calculate all required indicators on the dataframe."""
        # Make a copy to avoid modifying original
        data = df.copy()
        
        # EMAs
        data['EMA9'] = data['close'].ewm(span=self.config.ema_fast, adjust=False).mean()
        data['EMA21'] = data['close'].ewm(span=self.config.ema_slow, adjust=False).mean()
        data['EMA50'] = data['close'].ewm(span=self.config.ema_trend, adjust=False).mean()
        
        # ATR
        high_low = data['high'] - data['low']
        high_close = (data['high'] - data['close'].shift()).abs()
        low_close = (data['low'] - data['close'].shift()).abs()
        true_range = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
        data['ATR'] = true_range.rolling(self.config.atr_period).mean()
        
        # ADX
        plus_dm = data['high'].diff()
        minus_dm = data['low'].diff().abs() * -1
        plus_dm = plus_dm.where((plus_dm > 0) & (plus_dm > minus_dm.abs()), 0)
        minus_dm = minus_dm.abs().where((minus_dm.abs() > 0) & (minus_dm.abs() > plus_dm), 0)
        
        tr_smooth = true_range.ewm(span=self.config.adx_period, adjust=False).mean()
        plus_di = 100 * (plus_dm.ewm(span=self.config.adx_period, adjust=False).mean() / tr_smooth)
        minus_di = 100 * (minus_dm.ewm(span=self.config.adx_period, adjust=False).mean() / tr_smooth)
        
        dx = 100 * (plus_di - minus_di).abs() / (plus_di + minus_di + 1e-10)
        data['ADX'] = dx.ewm(span=self.config.adx_period, adjust=False).mean()
        data['PLUS_DI'] = plus_di
        data['MINUS_DI'] = minus_di
        
        # RSI
        delta = data['close'].diff()
        gain = delta.where(delta > 0, 0).rolling(self.config.rsi_period).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(self.config.rsi_period).mean()
        rs = gain / (loss + 1e-10)
        data['RSI'] = 100 - (100 / (1 + rs))
        
        # Bar range
        data['bar_range'] = data['high'] - data['low']
        
        # Trend labels
        data['uptrend'] = data['EMA9'] > data['EMA21']
        data['strong_uptrend'] = (data['EMA9'] > data['EMA21']) & (data['EMA21'] > data['EMA50'])
        data['strong_downtrend'] = (data['EMA9'] < data['EMA21']) & (data['EMA21'] < data['EMA50'])
        
        return data
        
    def _is_pullback(self, data: pd.DataFrame, idx: int, direction: str) -> bool:
        """Check if recent bars show a pullback in the trend direction."""
        if idx < self.config.pullback_bars:
            return False
            
        lookback = self.config.pullback_bars
        recent_closes = data['close'].iloc[idx-lookback:idx+1]
        
        if direction == "LONG":
            # For long pullback, price should have dipped below EMA9 recently
            recent_lows = data['low'].iloc[idx-lookback:idx]
            ema9_values = data['EMA9'].iloc[idx-lookback:idx]
            touched_ema = (recent_lows <= ema9_values).any()
            return touched_ema
        else:
            # For short pullback, price should have spiked above EMA9 recently
            recent_highs = data['high'].iloc[idx-lookback:idx]
            ema9_values = data['EMA9'].iloc[idx-lookback:idx]
            touched_ema = (recent_highs >= ema9_values).any()
            return touched_ema
            
    def _check_ema_reclaim(self, data: pd.DataFrame, idx: int) -> Optional[Tuple[str, float]]:
        """Check for EMA reclaim signal.
        
        EMA Reclaim Long: Price was below EMA9, now closes above it in uptrend
        EMA Reclaim Short: Price was above EMA9, now closes below it in downtrend
        """
        if idx < 2:
            return None
            
        row = data.iloc[idx]
        prev_row = data.iloc[idx - 1]
        
        close = row['close']
        ema9 = row['EMA9']
        ema21 = row['EMA21']
        prev_close = prev_row['close']
        prev_ema9 = prev_row['EMA9']
        
        # Long: Was below EMA9, now above, and EMA9 > EMA21 (uptrend)
        if prev_close < prev_ema9 and close > ema9 and ema9 > ema21:
            confidence = 0.65
            # Boost confidence if strong trend
            if row.get('strong_uptrend', False):
                confidence += 0.10
            if row['ADX'] > self.config.adx_strong_trend:
                confidence += 0.05
            return ("LONG", confidence)
            
        # Short: Was above EMA9, now below, and EMA9 < EMA21 (downtrend)
        if prev_close > prev_ema9 and close < ema9 and ema9 < ema21:
            confidence = 0.65
            # Boost confidence if strong trend
            if row.get('strong_downtrend', False):
                confidence += 0.10
            if row['ADX'] > self.config.adx_strong_trend:
                confidence += 0.05
            return ("SHORT", confidence)
            
        return None
        
    def _check_trend_continuation(self, data: pd.DataFrame, idx: int) -> Optional[Tuple[str, float]]:
        """Check for trend continuation signal after pullback."""
        if idx < self.config.pullback_bars + 1:
            return None
            
        row = data.iloc[idx]
        
        # Need strong ADX for trend continuation
        if row['ADX'] < self.config.adx_trend_threshold:
            return None
            
        # Long continuation: Uptrend + pullback to EMA + RSI not overbought
        if row['uptrend'] and self._is_pullback(data, idx, "LONG"):
            if row['RSI'] < self.config.rsi_overbought:
                confidence = 0.60
                if row['ADX'] > self.config.adx_strong_trend:
                    confidence += 0.10
                if row.get('strong_uptrend', False):
                    confidence += 0.05
                return ("LONG", confidence)
                
        # Short continuation: Downtrend + pullback to EMA + RSI not oversold
        if not row['uptrend'] and self._is_pullback(data, idx, "SHORT"):
            if row['RSI'] > self.config.rsi_oversold:
                confidence = 0.60
                if row['ADX'] > self.config.adx_strong_trend:
                    confidence += 0.10
                if row.get('strong_downtrend', False):
                    confidence += 0.05
                return ("SHORT", confidence)
                
        return None
        
    def _calculate_stops(
        self, 
        direction: str, 
        entry_price: float, 
        atr: float
    ) -> Tuple[float, float]:
        """Calculate stop loss and take profit levels."""
        # Stop distance based on ATR, capped by config
        stop_distance = atr * self.config.stop_atr_multiplier
        stop_distance = max(self.config.min_stop_points, stop_distance)
        stop_distance = min(self.config.max_stop_points, stop_distance)
        
        # Round to tick size (0.25 for ES)
        stop_distance = round(stop_distance / 0.25) * 0.25
        
        # Take profit as multiple of stop distance
        tp_distance = stop_distance * self.config.take_profit_multiplier
        tp_distance = round(tp_distance / 0.25) * 0.25
        
        if direction == "LONG":
            stop_loss = entry_price - stop_distance
            take_profit = entry_price + tp_distance
        else:
            stop_loss = entry_price + stop_distance
            take_profit = entry_price - tp_distance
            
        return stop_loss, take_profit
        
    def generate_signal(
        self, 
        data: pd.DataFrame, 
        bar_idx: int,
        current_position: int = 0
    ) -> ThirtyMinuteSignal:
        """Generate a trading signal for the given bar.
        
        Args:
            data: DataFrame with OHLCV data (indicators will be calculated)
            bar_idx: Index of current bar to evaluate
            current_position: Current position size (0 = flat, >0 = long, <0 = short)
            
        Returns:
            ThirtyMinuteSignal with action, direction, stops, etc.
        """
        # Calculate indicators if not present
        if 'EMA9' not in data.columns:
            data = self._calculate_indicators(data)
            
        row = data.iloc[bar_idx]
        timestamp = data.index[bar_idx] if hasattr(data.index[bar_idx], 'strftime') else datetime.now()
        
        # Check daily reset
        self._check_daily_reset(timestamp)
        
        # Default: HOLD
        signal = ThirtyMinuteSignal(
            timestamp=timestamp,
            action="HOLD",
            direction="FLAT",
            signal_type="NO_SIGNAL",
            confidence=0.0,
            stop_loss=0.0,
            take_profit=0.0,
            entry_price=row['close'],
            metadata={}
        )
        
        # Build metadata
        metadata = {
            'close': row['close'],
            'ema9': row['EMA9'],
            'ema21': row['EMA21'],
            'ema50': row.get('EMA50', 0),
            'atr': row['ATR'],
            'adx': row['ADX'],
            'rsi': row['RSI'],
            'bar_range': row.get('bar_range', 0),
            'bar_idx': bar_idx,
        }
        
        # Check warmup
        if bar_idx < self.config.warmup_bars:
            signal.signal_type = "WARMUP"
            signal.metadata = metadata
            return signal
            
        self._warmup_complete = True
        
        # Check filters
        block_reasons = []
        
        # Zero range bar
        if self.config.skip_zero_range and row.get('bar_range', 1) == 0:
            block_reasons.append("ZERO_RANGE")
            
        # Min bar range
        if row.get('bar_range', 999) < self.config.min_bar_range:
            block_reasons.append("SMALL_BAR")
            
        # ATR validity
        if pd.isna(row['ATR']) or row['ATR'] <= 0:
            block_reasons.append("INVALID_ATR")
            
        # ADX threshold - need trending market
        if row['ADX'] < self.config.adx_trend_threshold:
            block_reasons.append("LOW_ADX")
            
        # Max trades per day
        if self._trades_today >= self.config.max_trades_per_day:
            block_reasons.append("MAX_TRADES")
            
        # Cooldown
        if self._last_signal_bar is not None:
            bars_since_signal = bar_idx - self._last_signal_bar
            if bars_since_signal < self.config.cooldown_bars:
                block_reasons.append("COOLDOWN")
                
        # If any filters block, return HOLD
        if block_reasons:
            signal.signal_type = ",".join(block_reasons)
            signal.metadata = metadata
            return signal
            
        # Check for signals (only if flat)
        if current_position == 0:
            direction = None
            confidence = 0.0
            signal_type = "NO_SIGNAL"
            
            # Check EMA reclaim first (higher priority)
            if self.config.enable_ema_reclaim:
                result = self._check_ema_reclaim(data, bar_idx)
                if result:
                    direction, confidence = result
                    signal_type = "EMA_RECLAIM"
                    
            # Check trend continuation if no EMA reclaim
            if direction is None and self.config.enable_trend_continuation:
                result = self._check_trend_continuation(data, bar_idx)
                if result:
                    direction, confidence = result
                    signal_type = "TREND_CONTINUATION"
                    
            # Generate entry signal if we have direction with sufficient confidence
            if direction and confidence >= self.config.min_entry_confidence:
                entry_price = row['close']
                stop_loss, take_profit = self._calculate_stops(
                    direction, entry_price, row['ATR']
                )
                
                # Update state
                self._last_signal_bar = bar_idx
                self._trades_today += 1
                
                signal = ThirtyMinuteSignal(
                    timestamp=timestamp,
                    action="BUY" if direction == "LONG" else "SELL",
                    direction=direction,
                    signal_type=signal_type,
                    confidence=confidence,
                    stop_loss=stop_loss,
                    take_profit=take_profit,
                    entry_price=entry_price,
                    metadata={
                        **metadata,
                        'signal_type': signal_type,
                        'stop_distance': abs(entry_price - stop_loss),
                        'tp_distance': abs(take_profit - entry_price),
                    }
                )
                
                logger.info(
                    f"📊 30M Signal: {signal_type} {direction} @ {entry_price:.2f} "
                    f"SL={stop_loss:.2f} TP={take_profit:.2f} ADX={row['ADX']:.1f}"
                )
                
        signal.metadata = metadata
        return signal
        
    def should_exit(
        self, 
        data: pd.DataFrame, 
        bar_idx: int,
        entry_bar_idx: int,
        direction: str,
        entry_price: float,
        stop_loss: float,
        take_profit: float
    ) -> Tuple[bool, str, float]:
        """Check if position should be exited.
        
        Returns:
            Tuple of (should_exit, reason, exit_price)
        """
        row = data.iloc[bar_idx]
        
        # Check max hold time
        bars_held = bar_idx - entry_bar_idx
        if bars_held >= self.config.max_hold_bars:
            return True, "MAX_HOLD_TIME", row['close']
            
        # Check stop loss
        if direction == "LONG":
            if row['low'] <= stop_loss:
                return True, "STOP_LOSS", stop_loss
            if row['high'] >= take_profit:
                return True, "TAKE_PROFIT", take_profit
        else:  # SHORT
            if row['high'] >= stop_loss:
                return True, "STOP_LOSS", stop_loss
            if row['low'] <= take_profit:
                return True, "TAKE_PROFIT", take_profit
                
        # Check trend flip exit
        if self.config.require_trend_alignment:
            if direction == "LONG" and row['EMA9'] < row['EMA21']:
                return True, "TREND_FLIP", row['close']
            if direction == "SHORT" and row['EMA9'] > row['EMA21']:
                return True, "TREND_FLIP", row['close']
                
        return False, "", 0.0
